name: Deploy Pages

permissions:
  pages: write
  id-token: write

on:
  push:
    branches: ['main']
  workflow_dispatch:
  workflow_call:

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - uses: actions/checkout@v6
      - uses: ./.github/actions/setup
      - name: Build documentation
        run: pnpm build:docs
      - name: Run tests
        run: pnpm vitest run --coverage
      - name: Copy files to docs
        run: |
          mkdir -p docs/coverage
          cp -r coverage/* docs/coverage/
      - name: Configure Pages
        uses: actions/configure-pages@45bfe0192ca1faeb007ade9deae92b16b8254a0d # v6
      - name: Upload documentation artifact
        uses: actions/upload-pages-artifact@fc324d3547104276b827a68afc52ff2a11cc49c9 # v5
        with:
          path: ./docs
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@cd2ce8fcbc39b97be8ca5fce6e763baed58fa128 # v5
